# Configuração da URL do banco (Troque 'nome_do_seu_banco' pelo banco que você criou no Postgres)
spring.datasource.url=jdbc:postgresql://localhost:5423/nome_do_seu_banco
spring.datasource.username=seu_usuario_do_postgres
spring.datasource.password=sua_senha_do_postgres

# Hibernate cria e atualiza as tabelas automaticamente com base nos seus @Entity
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true